name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: Swatinem/rust-cache@v2

    - name: Lint
      run: cargo clippy -- -D warnings

    - name: Format
      run: cargo fmt -- --check

    - name: Build
      run: cargo build

    - name: Run tests
      run: cargo test

    # Run benchmarks as tests because we're not interested in analyzing
    # performance in the CI build, we just want to make sure they work.
    - name: Run benchmarks
      run: cargo test --benches
